// src/tui-solid/components/thinking-indicator.tsx
import { createSignal, onCleanup, onMount } from "solid-js";
import { useTheme } from "@tui-solid/context/theme";
import {
  THINKING_SPINNER_FRAMES,
  THINKING_SPINNER_INTERVAL,
} from "@constants/tui-components";

interface ThinkingIndicatorProps {
  message: string;
}

export function ThinkingIndicator(props: ThinkingIndicatorProps) {
  const theme = useTheme();
  const [frame, setFrame] = createSignal(0);

  let intervalId: ReturnType<typeof setInterval> | null = null;

  onMount(() => {
    intervalId = setInterval(() => {
      setFrame((prev) => (prev + 1) % THINKING_SPINNER_FRAMES.length);
    }, THINKING_SPINNER_INTERVAL);
  });

  onCleanup(() => {
    if (intervalId) {
      clearInterval(intervalId);
    }
  });

  return (
    <box flexDirection="row">
      <text fg={theme.colors.modeThinking}>
        {THINKING_SPINNER_FRAMES[frame()]}{" "}
      </text>
      <text fg={theme.colors.modeThinking}>{props.message}</text>
    </box>
  );
}

// src/tui/components/log-panel/thinking-indicator.tsx
/**
 * Thinking Indicator Component
 */

import React, { useState, useEffect } from "react";
import { Box, Text } from "ink";
import type { ThinkingIndicatorProps } from "@/types/tui";
import {
  THINKING_SPINNER_FRAMES,
  THINKING_SPINNER_INTERVAL,
} from "@constants/tui-components";

export function ThinkingIndicator({
  message,
}: ThinkingIndicatorProps): React.ReactElement {
  const [frame, setFrame] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setFrame((prev) => (prev + 1) % THINKING_SPINNER_FRAMES.length);
    }, THINKING_SPINNER_INTERVAL);
    return () => clearInterval(timer);
  }, []);

  return (
    <Box>
      <Text color="magenta">{THINKING_SPINNER_FRAMES[frame]} </Text>
      <Text color="magenta">{message}</Text>
    </Box>
  );
}
