// src/tui-solid/components/feedback/bouncing-loader.tsx
import { createSignal, onCleanup, onMount, For } from "solid-js";
import { TextAttributes } from "@opentui/core";

const LOADER_COLORS = [
  "#ff00ff",
  "#ff33ff",
  "#cc66ff",
  "#9966ff",
  "#6699ff",
  "#33ccff",
  "#00ffff",
  "#33ffcc",
] as const;

const LOADER_CONFIG = {
  dotCount: 8,
  frameInterval: 100,
  dotChar: "●",
  emptyChar: "○",
} as const;

interface DotInfo {
  char: string;
  color: string;
  dim: boolean;
}

export function BouncingLoader() {
  const [position, setPosition] = createSignal(0);
  const [direction, setDirection] = createSignal(1);

  let intervalId: ReturnType<typeof setInterval> | null = null;

  onMount(() => {
    intervalId = setInterval(() => {
      const dir = direction();
      const prev = position();
      const next = prev + dir;

      if (next >= LOADER_CONFIG.dotCount - 1) {
        setDirection(-1);
        setPosition(LOADER_CONFIG.dotCount - 1);
        return;
      }

      if (next <= 0) {
        setDirection(1);
        setPosition(0);
        return;
      }

      setPosition(next);
    }, LOADER_CONFIG.frameInterval);
  });

  onCleanup(() => {
    if (intervalId) {
      clearInterval(intervalId);
    }
  });

  const dots = (): DotInfo[] => {
    const pos = position();
    return Array.from({ length: LOADER_CONFIG.dotCount }, (_, i) => {
      const distance = Math.abs(i - pos);
      const isActive = distance === 0;
      const isTrail = distance <= 2;
      const colorIndex = i % LOADER_COLORS.length;
      const color = LOADER_COLORS[colorIndex];

      return {
        char:
          isActive || isTrail ? LOADER_CONFIG.dotChar : LOADER_CONFIG.emptyChar,
        color,
        dim: !isActive && !isTrail,
      };
    });
  };

  return (
    <box flexDirection="row">
      <For each={dots()}>
        {(dot) => (
          <text
            fg={dot.color}
            attributes={dot.dim ? TextAttributes.DIM : TextAttributes.NONE}
          >
            {dot.char}
          </text>
        )}
      </For>
    </box>
  );
}

// src/tui/components/BouncingLoader.tsx
/**
 * Bouncing Loader Component
 *
 * A horizontal bouncing loader with gradient colors.
 * The active dot bounces back and forth with a colorful trail.
 */

import React, { useEffect, useState } from "react";
import { Text } from "ink";

const LOADER_COLORS = [
  "#ff00ff", // magenta
  "#ff33ff", // light magenta
  "#cc66ff", // purple
  "#9966ff", // violet
  "#6699ff", // blue-violet
  "#33ccff", // cyan
  "#00ffff", // cyan bright
  "#33ffcc", // teal
] as const;

const LOADER_CONFIG = {
  dotCount: 8,
  frameInterval: 100,
  dotChar: "●",
  emptyChar: "○",
} as const;

export function BouncingLoader(): React.ReactElement {
  const [position, setPosition] = useState(0);
  const [direction, setDirection] = useState(1);

  useEffect(() => {
    const timer = setInterval(() => {
      setPosition((prev) => {
        const next = prev + direction;

        if (next >= LOADER_CONFIG.dotCount - 1) {
          setDirection(-1);
          return LOADER_CONFIG.dotCount - 1;
        }

        if (next <= 0) {
          setDirection(1);
          return 0;
        }

        return next;
      });
    }, LOADER_CONFIG.frameInterval);

    return () => clearInterval(timer);
  }, [direction]);

  const dots = Array.from({ length: LOADER_CONFIG.dotCount }, (_, i) => {
    const distance = Math.abs(i - position);
    const isActive = distance === 0;
    const isTrail = distance <= 2;

    // Get color based on position in the gradient
    const colorIndex = i % LOADER_COLORS.length;
    const color = LOADER_COLORS[colorIndex];

    return {
      char:
        isActive || isTrail ? LOADER_CONFIG.dotChar : LOADER_CONFIG.emptyChar,
      color,
      dimColor: !isActive && !isTrail,
    };
  });

  return (
    <Text>
      {dots.map((dot, i) => (
        <Text key={i} color={dot.color} dimColor={dot.dimColor}>
          {dot.char}
        </Text>
      ))}
    </Text>
  );
}
